import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
import { CardImage } from '@/components/Card'
import { Button } from '@/components/Button'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='flex items-center justify-center h-[100vh] w-full'>
          <div className='bg-black w-[818px] h-[627px] rounded-md'>
            <div className='w-full flex justify-center space-x-4 py-10 my-10'>
              <div>
                <CardImage src='/card-title.png' />
              </div>
              <div>
                <CardImage src='/card-2.png' />
              </div>
              <div>
                <CardImage src='/card-A.png' />
              </div>
            </div>
            <div className='flex justify-center space-x-4'>
              <div className='w-[330px] h-[76px] bg-[#1B2233] p-2 border border-[#FE0000] rounded-[7px] flex flex-col justify-between'>
                <div className='flex justify-between'>
                  <div className='flex items-center w-[40px] h-[25px] bg-[#283343] rounded-[7px] justify-center'>
                    <span className=" text-[#55657E] text-center text-[12px] font-[600]">Min</span>
                  </div>
                  <span className='flex'>
                    <Image
                      className="mr-4"
                      src={"/t-icon.png"}
                      alt="card"
                      width={19}
                      height={19}

                    />
                    <h2 className='font-[700] text-[18px] text-[#FFFFFF]'>0.91999970</h2>
                  </span>
                  <div className='flex items-center w-[40px] h-[25px] bg-[#283343] rounded-[7px] justify-center'>
                    <span className=" text-[#55657E] text-center text-[12px] font-[600]">1/2</span>
                  </div>

                </div>
                <div className='flex justify-between'>
                <div className='flex items-center w-[40px] h-[25px] bg-[#283343] rounded-[7px] justify-center'>
                    <span className=" text-[#55657E] text-center text-[12px] font-[600]">Max</span>
                  </div>
                  <span className='flex'>
                    <h2 className='font-[600] text-[14px] text-[#55657E] ml-2'>$0.9199997</h2>
                  </span>
                  <div className='flex items-center w-[40px] h-[25px] bg-[#283343] rounded-[7px] justify-center'>
                    <span className=" text-[#55657E] text-center text-[12px] font-[600]">2x</span>
                  </div>

                </div>
              </div>
              <Button classname='w-[330px] h-[76px] bg-[#1B2233] text-[#FE0000] border border-[#4B5B74] rounded-[7px] uppercase font-semibold text-[18px] text-center' title='Red' />
            </div>
            <div className='flex justify-center space-x-4 py-3'>
              <Button classname='w-[330px] h-[76px] bg-[#2283F6] text-[#FFFF] border border-[#4B5B74] rounded-[7px]  uppercase font-semibold text-[18px] text-center' title='start' />
              <Button classname='w-[330px] h-[76px] bg-[#1B2233] text-[#297FE5] border border-[#4B5B74] rounded-[7px] uppercase font-semibold text-[18px] text-center' title='Black' />
            </div>
          </div>

        </div>
      </main>
    </>
  )
}
